### PR TITLE
Fix HDInsight sizing bug #1168

### PR DESCRIPTION
**Pull request by lawrencegripper**

### CODE REVIEW

**Comment by marrobi** [comment]
Yup, 

> Hadoop achieves high availability and reliability by replicating services and data across multiple nodes in a cluster. However standard distributions of Hadoop typically have only a single head node. Any outage of the single head node can cause the cluster to stop working. HDInsight provides two headnodes to improve Hadoop's availability and reliability.

https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-high-availability-linux

**Comment by lawrencegripper** [comment]
Thanks @marrobi good spot, I've fixed that up now.

**Comment by jjcollinge** [comment]
LGTM

**Comment by jjcollinge** [comment]
@lawrencegripper to track D series to E series in a new issue

**Pull request merged**
