### PR TITLE
Fix `hadoop` not found error in Batch container

### LINKED ISSUE #1113: Azure Batch tasks return a failure
Azure Batch redurns an exit code of 1, hence job show as a failure.

### PR DESCRIPTION
**Pull request by lawrencegripper**
This is the first step to resolve #1113 

- [x] Copy the binary and data from the cluster in the init script
- [x] Update the container to have these loaded on to the PATH variable

### CODE REVIEW

**Comment by lawrencegripper** [comment]
@opencb/azure what do people think of this workaround? I didn't want to edit the entrypoint of confuse the task commandline by appending extra hadoop setup each time so I've edited `bash.bashrc` to run the `hadoop` configuration when the `bash` shell starts. 

This needs to have a test run next week before we merge but hopefully should be in a relatively good place for testing.

**Comment by lawrencegripper** [comment]
Based on discussions on #1113 I've moved approaches here to try and make this a nicer experience - moving to using `apt` to install the `hdp` stuff.

**Comment by lawrencegripper** [comment]
Current state on the PR is that it errors running the `hadoop` binary but this error does indicate the the binary has been installed and is on the PATH which is good news!

```
Step 10/11 : RUN hadoop
 ---> Running in 4bd329860c77
Error: JAVA_HOME is not set and could not be found.
```

To repro the error pull the branch and run `make` from the docker directory.

**Comment by martinpeck** [comment]
@jjcollinge to spin up environment and test that this is now fixed.

**Comment by lawrencegripper** [comment]
Closing this in favor of using `ssh` to connect to an already configured cluster node and executing the commands.

**Pull request closed without merging**
