### PR TITLE
Move docker files to Oracle Java 8 & Debian

### LINKED ISSUE #1076: Mongo DB read hangs while reading from catalog from Daemon to read and update

### PR DESCRIPTION
**Pull request by lawrencegripper**
Alpine isn't a supported image for OpenJDK so this involved moving to `Debian Stretch-slim`

Sadly doesn't re-solve #1076 :(

### CODE REVIEW

**Comment by jjcollinge** [comment]
Code looks good but I think only a few of the images have been properly tested. Once I've finished up with the TF/ARM stuff I'm working on at the moment I'll try run the tests against all the images.

**Comment by lawrencegripper** [comment]
I've merged in the work from `azure` branch now so hopefully next build will include latest code.

**Comment by jjcollinge** [comment]
LGTM

**Comment by lawrencegripper** [comment]
Just re-merging changes from the Azure branch then build should pass and will merge this PR

**Comment by lawrencegripper** [comment]
I've re-merged again to catch up with `azure` branch. @marrobi once the build is completed should be good to merge this PR

**Pull request merged**
