### PR TITLE
TASK-4593 HRDetect analysis not working with the current R library

### PR DESCRIPTION
**Pull request by jtarraga**
Fix HRDetect analysis

### CODE REVIEW

**Comment by jtarraga** [comment]
Task linked: [TASK-4593 HRDetect analysis not working with the current R library](https://app.clickup.com/t/36631768/TASK-4593)

**Review by juanfeSanahuja — APPROVED** [review]

**Review by juanfeSanahuja — COMMENTED** [review]
The process to generate Ext-tools docker fails.... can you review?

**Review by juanfeSanahuja — CHANGES_REQUESTED** [review]
Check docker generation

**Comment by jtarraga** [comment]
> Check docker generation

I relaunched the CI/CD push docker image for the ext-tools, and it worked without any errors.

**Review by juanfeSanahuja — APPROVED** [review]

**Pull request merged**
