### PR TITLE
HealthCheck cache

### PR DESCRIPTION
**Pull request by wbari**

### CODE REVIEW

**Comment by wbari** [comment]
@marrobi could you please review ARM changes in this PR. Its mainly, I have added a new variable "healthCheck:
  interval : 30 # seconds to get actual healthCheck than cache" in opencga "configuration.yml" file and make changes in ARM and docker to configure that value. 
Thanks

**Comment by wbari** [comment]
related to #1152

**Comment by lawrencegripper** [comment]
@wbari awesome work on the PR. A couple of tweaks needed to get this one up and running. 

The `healthcheck` parameter added in the top level ARM template needs to be added into the receiving `deamonvm` template too and then added into the [`initCmd` variable](https://github.com/opencb/opencga/blob/azure/opencga-app/app/scripts/azure/arm/daemonvm/azuredeploy.json#L146)

This should look like: 

```json
        "healthCheckInterval": {
            "type": "int",
            "defaultValue": "30",
            "metadata": {
                "description": "HealthCheck cache interval value in seconds."
            }
        } 
```

under parameters in `./daemonvm/azuredeploy.json` and then the `initCmd` updated to add the extra environment variable like so:

```json
[concat('docker run --mount type=bind,src=/media/primarynfs,dst=/opt/volume -e OPENCGA_PASS=',parameters('openCgaAdminPassword'), -e HEALTH_CHECK_INTERVAL=',parameters('healthCheckInterval'), ....
```

Then you should be all set, I'm around all of today so give me a yell and I can do a test deployment whenever suits.

**Comment by lawrencegripper** [comment]
One thing to note is that the healthcheck did seem to fail on my instance once deployed to this is likely something that needs to be reviewed.

**Pull request merged**
